controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
courses:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        # это значение может быть абсолютным путем или URL
        path: /courses
        permanent: true